version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'